# file: .github/workflows/show-directory.yml
name: show-directory

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          pwd
          ls -la
          cat Makefile
          make say-hello
